<<<if{{{grafana/enabled}}}>>>
  grafana:
    image: {{{grafana/repository}}}:{{{grafana/version}}}
    environment:
      GF_SERVER_ROOT_URL: "https://{{{nginx/host_name_default}}}/grafana/"
      GF_INSTALL_PLUGINS: grafana-clock-panel,redis-datasource
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SERVE_FROM_SUB_PATH: "true"
      GF_SERVER_PROTOCOL: http
      GF_AUTH_BASIC_ENABLED: "false"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - grafanadata:/var/lib/grafana
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - "{{{nginx/port/project+10}}}:3000"
<<<endif>>>
    <<<if{{{grafana/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>

<<<if{{{grafana/enabled}}}>>>
  loki:
    image: grafana/loki:2.9.10
    command: -config.file=/etc/loki/local-config.yaml
    user: root
    volumes:
      - lokidata:/loki
  <<<endif>>>
    <<<if{{{grafana/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>

<<<if{{{grafana/enabled}}}>>>
  promtail:
    image: grafana/promtail:2.9.10
    volumes:
      - ./src/var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
  <<<endif>>>
    <<<if{{{grafana/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>