version: "3.7"
services:
  nginx:
    build:
      context: ctx
      dockerfile: Dockerfile
    volumes:
      - ./ctx/proxy.conf:/etc/nginx/nginx.conf:delegated
      - ./ctx/:/sslcert/:delegated
    ports:
      - {{{INTERFACE_IP}}}80:80
      - {{{INTERFACE_IP}}}443:443
      - {{{INTERFACE_IP}}}35729:35729
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - {{{INTERFACE_IP}}}8025:8025
