{{{include snippets/docker-compose-container-name.yml}}}
services:
  {{{include snippets/docker-compose-php.yml}}}
  {{{include snippets/docker-compose-php-xdebug.yml}}}
  {{{include snippets/docker-compose-nginx.yml}}}
  {{{include snippets/docker-compose-db.yml}}}
  {{{include snippets/docker-compose-db2.yml}}}
  {{{include snippets/docker-compose-nodejs.yml}}}
  {{{include snippets/docker-compose-elasticsearch.yml}}}
  {{{include snippets/docker-compose-opensearch.yml}}}
  {{{include snippets/docker-compose-redis.yml}}}
  {{{include snippets/docker-compose-rabbitmq.yml}}}
  {{{include snippets/docker-compose-phpmyadmin.yml}}}
  {{{include snippets/docker-compose-phpmyadmin2.yml}}}

<<<if{{{search/elasticsearch/dashboard/enabled}}}>>>
  kibana:
    platform: linux/x86_64
    image: {{{search/elasticsearch/dashboard/repository}}}:{{{search/elasticsearch/version}}}
    environment:
      SERVER_BASEPATH: /kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "{{{nginx/port/project+3}}}:5601"
    depends_on:
      - elasticsearch
<<<endif>>>
    <<<if{{{search/elasticsearch/dashboard/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>

<<<if{{{search/opensearch/dashboard/enabled}}}>>>
  opensearchdashboard:
    platform: linux/x86_64
    image: {{{search/opensearch/dashboard/repository}}}:{{{search/opensearch/version}}}
    environment:
      SERVER_BASEPATH: /opensearch-dashboard
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    ports:
      - "{{{nginx/port/project+3}}}:5601"
    depends_on:
      - opensearch
<<<endif>>>
    <<<if{{{search/opensearch/dashboard/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>
  
<<<if{{{magento/mftf/enabled}}}>>>
  selenium:
    image: selenium/standalone-chrome:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
      {{{nginx/host_gateways}}}
    ports:
      - "{{{nginx/port/project+8}}}:7900"
    shm_size: '2g'
    depends_on:
      - php
<<<endif>>>
    <<<if{{{magento/mftf/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>

<<<if{{{varnish/enabled}}}>>>
  varnish:
    image: {{{varnish/repository}}}:{{{varnish/version}}}
    volumes:
      - ./src/{{{varnish/config_file}}}:/etc/varnish/default.vcl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      {{{nginx/host_gateways}}}
    command: "-p default_keep=300"
    environment:
      VARNISH_HTTP_PORT: {{{nginx/port/project+9}}}
      VARNISH_SIZE: 1G
    ports:
      - "{{{nginx/port/project+9}}}:{{{nginx/port/project+9}}}"
    depends_on:
      - nginx
<<<endif>>>
<<<if{{{varnish/enabled}}}{{{isolation/enabled}}}>>>networks:
  - isolated<<<endif>>>

volumes:
  dbdata:
  <<<if{{{db2/enabled}}}>>>dbdata2:<<<endif>>>
  <<<if{{{search/elasticsearch/enabled}}}>>>elasticsearch_vlm_{{{search/elasticsearch/version}}}:<<<endif>>>
  <<<if{{{search/opensearch/enabled}}}>>>opensearch_vlm_{{{search/opensearch/version}}}:<<<endif>>>
<<<if{{{isolation/enabled}}}>>>
networks:
  opened:
    driver: bridge
  isolated:
    driver: bridge
    internal: true
<<<endif>>>