version: "3.8"
name: {{{CONTAINER_NAME_PREFIX}}}{{{PROJECT_NAME}}}
services:
  nodejs:
    build:
      context: ctx
      dockerfile: nodejs.Dockerfile
    tty: true
    volumes: &appvolumes
      - ./src:/var/www/html:cached
      - ./ssh/id_rsa:/var/www/.ssh/id_rsa:ro
      - ./ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "{{{PWA_BACKEND_URL}}}:host-gateway"

  nginx:
    build:
      context: ctx
      dockerfile: nginx.Dockerfile
    ports:
      - "{{{NGINX_PROJECT_PORT}}}:80"
      - "{{{NGINX_PROJECT_PORT_SSL}}}:443"
    volumes:
      - ./src:/var/www/html:delegated
      - ./ctx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
