{{{include snippets/docker-compose/container-name.yml}}}
services:
  {{{include snippets/docker-compose/php.yml}}}
  {{{include snippets/docker-compose/nginx.yml}}}
  {{{include snippets/docker-compose/db.yml}}}
  {{{include snippets/docker-compose/db2.yml}}}
  {{{include snippets/docker-compose/redis.yml}}}
  {{{include snippets/docker-compose/rabbitmq.yml}}}
  {{{include snippets/docker-compose/phpmyadmin.yml}}}
  {{{include snippets/docker-compose/phpmyadmin2.yml}}}
  {{{include snippets/docker-compose/grafana-shopify.yml}}}

volumes:
  dbdata:
  <<<if{{{db2/enabled}}}>>>dbdata2:<<<endif>>>

{{{include snippets/docker-compose/networks.yml}}}