{{{include snippets/docker-compose-container-name.yml}}}
services:
  {{{include snippets/docker-compose-php.yml}}}
  {{{include snippets/docker-compose-nginx.yml}}}
  {{{include snippets/docker-compose-db.yml}}}
  {{{include snippets/docker-compose-db2.yml}}}
  {{{include snippets/docker-compose-redis.yml}}}
  {{{include snippets/docker-compose-rabbitmq.yml}}}
  {{{include snippets/docker-compose-phpmyadmin.yml}}}

<<<if{{{db2/phpmyadmin/enabled}}}>>>
  phpmyadmin2:
    image: {{{db2/phpmyadmin/repository}}}:{{{db2/phpmyadmin/version}}}
    environment:
      PMA_HOST: "db2"
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: "http://{{{nginx/host_name_default}}}/phpmyadmin2/"
      PMA_USER: root
      PMA_PASSWORD: {{{db2/root_password}}}
      UPLOAD_LIMIT: 2G
    ports:
      - "{{{nginx/port/project+7}}}:80"
<<<endif>>>
    <<<if{{{db2/phpmyadmin/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>

volumes:
  dbdata:
  <<<if{{{db2/enabled}}}>>>dbdata2:<<<endif>>>
<<<if{{{isolation/enabled}}}>>>
networks:
  opened:
    driver: bridge
  isolated:
    driver: bridge
    internal: true
<<<endif>>>